### ISSUE TITLE
Connection acquisition incorrectly assumes that there will be a waiter in the pool

### ISSUE THREAD

**Issue by willks** [vietj/reactive-pg-client#60] opened 2018-02-28 14:26 UTC
Hi,
  I keep getting this in my logs when running concurrent tests. It uses 5 concurrent users - and the exception observed is this with the ReactiveX flavour:

```
SEVERE: Unhandled exception
java.lang.NullPointerException
	at com.julienviet.pgclient.impl.ConnectionPool.lambda$check$1(ConnectionPool.java:165)
	at com.julienviet.pgclient.impl.ConnectionPool.doAcq(ConnectionPool.java:139)
	at com.julienviet.pgclient.impl.ConnectionPool.lambda$doAcq$0(ConnectionPool.java:150)
	at com.julienviet.pgclient.impl.InitCommand.handleMessage(InitCommand.java:93)
	at com.julienviet.pgclient.impl.SocketConnection.handleMessage(SocketConnection.java:233)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessageReceived(NetSocketImpl.java:351)
	at io.vertx.core.net.impl.NetClientImpl$1.handleMessage(NetClientImpl.java:242)
	at io.vertx.core.net.impl.NetClientImpl$1.handleMessage(NetClientImpl.java:239)
	at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:146)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:144)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:844)

```

My pool settings are:

```
        PgPoolOptions options = new PgPoolOptions()
                .setPort(5432)
                .setHost("vm")
                .setDatabase("xxxxx")
                .setUsername("yyyyy")
                .setPassword("zzzzz")
                .setConnectTimeout(100000)
                .setIdleTimeout(100000)
                .setCachePreparedStatements(true)
                .setLogActivity(true)
                .setReconnectAttempts(10)
                .setTcpFastOpen(true)
                .setMaxSize(25);
```

All queries issued return a Single, and I'm using the query code like this (rxPreparedQuery):

```
    public Single<T> get(UUID entityId, Identity identity) {
        Tuple binds = Tuple.of(entityId, identity.getIdentityId());
        return db.rxPreparedQuery("select * from " + typeParameterClass.getSimpleName().toLowerCase() +" where id=$1 and identityid=$2", binds).map(rowPgResult -> {
            if (rowPgResult.size() == 0) {
                return empty();
            }
            Row next1 = rowPgResult.iterator().next();
            return mapRow(next1);
        });
    };
```

The issue is intermittent, but as I remove my tests concurrency, the error appears less. Running the code more times seems to yield less errors. With a single user, on repeated tests the error will no longer appear.

Seems that this code gets triggered when I see it:

```
  public void handleMessage(InboundMessage msg) {
    if (msg.getClass() == ReadyForQuery.class) {
      ReadyForQuery readyForQuery = (ReadyForQuery) msg;
      completionHandler.handle(null);
      if (failure != null) {
        handler.handle(CommandResponse.failure(failure, readyForQuery.txStatus()));
      } else {
        handler.handle(CommandResponse.success(result, readyForQuery.txStatus()));
      }
    } else {
      System.out.println(getClass().getSimpleName() + " should handle message " + msg);
    }
  }
```

That is
```
        handler.handle(CommandResponse.failure(failure, readyForQuery.txStatus()));
```
has the status:   txStatus=IDLE

Not sure if related - or that if the error is because the PreparedStatement doesn't exist? I can't figure it out yet.

Any clues?

**Comment by vietj** [comment] 2018-02-28 15:00
can you provide a reproducer ? what if you don't use rx ?

**Comment by vietj** [comment] 2018-02-28 15:04
it's hard to make sense of this exception because:

ExtendedQueryResultHandler.java:45:
``` 
suspended = res.result();
```

and 

CommandBase.java:44
```
handler.handle(CommandResponse.failure(failure, readyForQuery.txStatus()))
```

and clearly `CommandResponse.failure(...)` does not return `null`

**Comment by willks** [comment] 2018-02-28 15:12
Yes maybe it's misleading. I'll try and write up a quick tests and test cases to reproduce. I'm migrating my project from Scala back to Java so it may be a few days as I get time.

Thanks for looking up.

**Comment by willks** [comment] 2018-03-02 02:42
@vietj I have not had time to create a proper test case for you just yet, however - I swapped over to the  default version (the Kotlin friendly one). I get the same issue regardless of the flavour.

Cheers

**Comment by vietj** [comment] 2018-03-02 07:40
let me know if you can provide more context because the stack trace does not make sense to me

**Comment by willks** [comment] 2018-03-02 09:52
@vietj You know, even though it logs this null, the app still is working fine. I'll keep testing this as I want to rule out anything stupid I may be doing - but I'll dedicate some time over the weekend to doing a replicable test. Either way, like I said - I'm sticking to this driver as it's the best out there by far

**Comment by vietj** [comment] 2018-03-02 09:56
@willks thanks for everything! we spent lot of time in the client to make it simple and efficient!

**Comment by willks** [comment] 2018-03-02 11:01
@vietj I tried the rest already - they all hang with the lightest load and one even required changes to the Postgres configuration!

I have a better hint now at the issue from this pic:

[https://ibb.co/mndBDH](url)

So it looks like the waiter is null? I dunno. I'll try and get on that test

```
private void check() {
    if (waiters.size() > 0) {
      doAcq(ar -> {
        if (ar.succeeded()) {
          PooledConnection proxy = ar.result();
          Future<Connection> waiter = waiters.poll();
          waiter.complete(proxy);
        } else {
          Future<Connection> waiter;
          while ((waiter = waiters.poll()) != null) {
            waiter.fail(ar.cause());
          }
        }
      });
    }
  }
```

**Comment by vietj** [comment] 2018-03-02 13:37
that would be a race condition in the pool under high load ?

**Comment by willks** [comment] 2018-03-02 14:13
@vietj Looks like. It's 5 threads, with 3 requests each. My tests use Scala (SBT) so all integration tests kick off at the same time. Every request does a "user" check based on JWT token, to verify identity. I plan to introduce a cache for this though. My current DA tier acquires connections from pool manually (and returns on error/success/exception) - but also tried using the automatic pool acquisition, which was the initial issue that I raised. The result is the same at this point.

In any case, I'm still developing my app and just ignoring it for now. Compared to the awesome work so far, I'm sure it's one of those "easy to fix" but "difficult to find" concurrency issues. The bane of development! As this is my private app (but high concurrency due use-case) - I have to to test and nut out issues.

**Comment by vietj** [comment] 2018-03-02 14:33
@willks you are totally right

**Comment by Ryan-ZA** [comment] 2018-03-03 23:04
I don't have reproducer code, but I know how to trigger this exception. Maybe it will make it easier to find.

If you start with a maxsize pool of 1, then run a query with a cursor, and then try to run another query before closing the cursor, then you will get this exact NullPointerException. 

Probably this is the same thing that is happening under high load - by chance all connections in the pool have a cursor open, and one additional request tries to run. A temporary workaround would be to have 1 pool that is only for cursors, and another pool that handles any queries done from within a cursor.

**Comment by willks** [comment] 2018-03-04 07:49
Well, here is a start, but it does reproduce it. 

https://github.com/willks/pgtest

Not sure if it's 100% right, but the exception happens. If the pool size is 1, I don't get the issue. Strange. 

Use "gradle run" to execute

**Comment by vietj** [comment] 2018-03-04 09:33
thanks, will have a look soon.

**Closed** 2018-03-04 21:28 UTC

**Comment by vietj** [comment] 2018-03-04 22:26
@willks I've fixed the bug you reported, can you check that master works fine with your branch ? (I've checked with your reproducer and it works fine)

**Comment by vietj** [comment] 2018-03-05 19:58
@willks once you have done this check, I can do a 0.5.2 release with the fix

**Comment by willks** [comment] 2018-03-06 01:26
@vietj Looks good!!

Thanks for this
